const data = {
    computers:  [
        {
            id: 1,
            name: 'PC GAMER SLASH',
            slug: 'pc-gamer-slash',
            category: 'AMD',
            image: '/images/pc1.png',
            price: 2200000,
            brand: 'AMD',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular pc',
            cpu: 'AMD Ryzen 5800X Procesador',
            motherboard: 'AMD X570 ATX Motherboard',
            ram: '32GB 3600Mhz DDR4 Dual Channel RAM',
            ssd: '2TB Nvme SSD',
            hdd: '3TB Seagate HDD',
            gpu: 'Nvidia RTX 3080TI GPU'    

        },
        {
            id: 2,
            name: 'PC GAMER BUDDY',
            slug: 'pc-gamer-buddy',
            category: 'AMD',
            image: '/images/pc3.png',
            price: 2200000,
            brand: 'AMD',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular pc',
            cpu: 'AMD Ryzen 5800X Procesador',
            motherboard: 'AMD X570 ATX Motherboard',
            ram: '32GB 3600Mhz DDR4 Dual Channel RAM',
            ssd: '2TB Nvme SSD',
            hdd: '3TB Seagate HDD',
            gpu: 'Nvidia RTX 3080TI GPU'    
        },
        {
            id: 3,
            name: 'PC GAMER NIWARO',
            slug: 'pc-gamer-niwaro',
            category: 'AMD',
            image: '/images/pc2.png',
            price: 2200000,
            brand: 'AMD',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular pc',
            cpu: 'AMD Ryzen 5800X Procesador',
            motherboard: 'AMD X570 ATX Motherboard',
            ram: '32GB 3600Mhz DDR4 Dual Channel RAM',
            ssd: '2TB Nvme SSD',
            hdd: '3TB Seagate HDD',
            gpu: 'Nvidia RTX 3080TI GPU'    
        },
        {
            id: 4,
            name: 'PC GAMER WOLF',
            slug: 'pc-gamer-wolf',
            category: 'AMD',
            image: './images/pc1.png',
            price: 2200000,
            brand: 'AMD',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular pc',
            cpu: 'AMD Ryzen 5800X Procesador',
            motherboard: 'AMD X570 ATX Motherboard',
            ram: '32GB 3600Mhz DDR4 Dual Channel RAM',
            ssd: '2TB Nvme SSD',
            hdd: '3TB Seagate HDD',
            gpu: 'Nvidia RTX 3080TI GPU'    
        },
        {
            id: 5,
            name: 'PC GAMER DASH',
            slug: 'pc-gamer-dash',
            category: 'AMD',
            image: '/images/pc4.png',
            price: 2200000,
            brand: 'AMD',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular pc',
            cpu: 'AMD Ryzen 5800X Procesador',
            motherboard: 'AMD X570 ATX Motherboard',
            ram: '32GB 3600Mhz DDR4 Dual Channel RAM',
            ssd: '2TB Nvme SSD',
            hdd: '3TB Seagate HDD',
            gpu: 'Nvidia RTX 3080TI GPU'    
        },
        {
            id: 6,
            name: 'PC GAMER DEAPTREAD',
            slug: 'pc-gamer-deaptread',
            category: 'AMD',
            image: './images/pc1.png',
            price: 2200000,
            brand: 'AMD',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular pc',
            cpu: 'AMD Ryzen 5800X Procesador',
            motherboard: 'AMD X570 ATX Motherboard',
            ram: '32GB 3600Mhz DDR4 Dual Channel RAM',
            ssd: '2TB Nvme SSD',
            hdd: '3TB Seagate HDD',
            gpu: 'Nvidia RTX 3080TI GPU'    
        },
    ],
    workstations:  [
        {
            id: 7,
            name: 'WORKSTATION SLASH',
            category: 'AMD',
            image: './images/pc1.png',
            price: 2200000,
            brand: 'AMD',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular pc',
            cpu: 'AMD Ryzen 5800X Procesador',
            motherboard: 'AMD X570 ATX Motherboard',
            ram: '32GB 3600Mhz DDR4 Dual Channel RAM',
            ssd: '2TB Nvme SSD',
            hdd: '3TB Seagate HDD',
            gpu: 'Nvidia RTX 3080TI GPU'    

        },
        {
            id: 8,
            name: 'WORKSTATION BUDDY',
            category: 'AMD',
            image: './images/pc3.png',
            price: 2200000,
            brand: 'AMD',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular pc',
            cpu: 'AMD Ryzen 5800X Procesador',
            motherboard: 'AMD X570 ATX Motherboard',
            ram: '32GB 3600Mhz DDR4 Dual Channel RAM',
            ssd: '2TB Nvme SSD',
            hdd: '3TB Seagate HDD',
            gpu: 'Nvidia RTX 3080TI GPU'    
        },
        {
            id: 9,
            name: 'WORKSTATION NIWARO',
            category: 'AMD',
            image: './images/pc2.png',
            price: 2200000,
            brand: 'AMD',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular pc',
            cpu: 'AMD Ryzen 5800X Procesador',
            motherboard: 'AMD X570 ATX Motherboard',
            ram: '32GB 3600Mhz DDR4 Dual Channel RAM',
            ssd: '2TB Nvme SSD',
            hdd: '3TB Seagate HDD',
            gpu: 'Nvidia RTX 3080TI GPU'    
        },
        {
            id: 10,
            name: 'WORKSTATION WOLF',
            category: 'AMD',
            image: './images/pc1.png',
            price: 2200000,
            brand: 'AMD',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular pc',
            cpu: 'AMD Ryzen 5800X Procesador',
            motherboard: 'AMD X570 ATX Motherboard',
            ram: '32GB 3600Mhz DDR4 Dual Channel RAM',
            ssd: '2TB Nvme SSD',
            hdd: '3TB Seagate HDD',
            gpu: 'Nvidia RTX 3080TI GPU'    
        },
        {
            id: 11,
            name: 'WORKSTATION DASH',
            category: 'AMD',
            image: '/images/pc4.png',
            price: 2200000,
            brand: 'AMD',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular pc',
            cpu: 'AMD Ryzen 5800X Procesador',
            motherboard: 'AMD X570 ATX Motherboard',
            ram: '32GB 3600Mhz DDR4 Dual Channel RAM',
            ssd: '2TB Nvme SSD',
            hdd: '3TB Seagate HDD',
            gpu: 'Nvidia RTX 3080TI GPU'    
        },
        {
            id: 12,
            name: 'WORKSTATION DEAPTREAD',
            category: 'AMD',
            image: './images/pc1.png',
            price: 2200000,
            brand: 'AMD',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular pc',
            cpu: 'AMD Ryzen 5800X Procesador',
            motherboard: 'AMD X570 ATX Motherboard',
            ram: '32GB 3600Mhz DDR4 Dual Channel RAM',
            ssd: '2TB Nvme SSD',
            hdd: '3TB Seagate HDD',
            gpu: 'Nvidia RTX 3080TI GPU'    
        },
    ],
    notebooks:  [
        {
            id: 13,
            name: 'NOTEBOOK SLASH',
            category: 'AMD',
            image: './images/nb1.png',
            price: 2200000,
            brand: 'AMD',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular pc',
            cpu: 'AMD Ryzen 5800X Procesador',
            motherboard: 'AMD X570 ATX Motherboard',
            ram: '32GB 3600Mhz DDR4 Dual Channel RAM',
            ssd: '2TB Nvme SSD',
            hdd: '3TB Seagate HDD',
            gpu: 'Nvidia RTX 3080TI GPU'    

        },
        {
            id: 14,
            name: 'NOTEBOOK BUDDY',
            category: 'AMD',
            image: './images/pc3.png',
            price: 2200000,
            brand: 'AMD',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular pc',
            cpu: 'AMD Ryzen 5800X Procesador',
            motherboard: 'AMD X570 ATX Motherboard',
            ram: '32GB 3600Mhz DDR4 Dual Channel RAM',
            ssd: '2TB Nvme SSD',
            hdd: '3TB Seagate HDD',
            gpu: 'Nvidia RTX 3080TI GPU'    
        },
        {
            id: 15,
            name: 'NOTEBOOK NIWARO',
            category: 'AMD',
            image: './images/pc2.png',
            price: 2200000,
            brand: 'AMD',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular pc',
            cpu: 'AMD Ryzen 5800X Procesador',
            motherboard: 'AMD X570 ATX Motherboard',
            ram: '32GB 3600Mhz DDR4 Dual Channel RAM',
            ssd: '2TB Nvme SSD',
            hdd: '3TB Seagate HDD',
            gpu: 'Nvidia RTX 3080TI GPU'    
        },
        {
            id: 16,
            name: 'NOTEBOOK WOLF',
            category: 'AMD',
            image: './images/pc1.png',
            price: 2200000,
            brand: 'AMD',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular pc',
            cpu: 'AMD Ryzen 5800X Procesador',
            motherboard: 'AMD X570 ATX Motherboard',
            ram: '32GB 3600Mhz DDR4 Dual Channel RAM',
            ssd: '2TB Nvme SSD',
            hdd: '3TB Seagate HDD',
            gpu: 'Nvidia RTX 3080TI GPU'    
        },
        {
            id: 17,
            name: 'NOTEBOOK DASH',
            category: 'AMD',
            image: '/images/pc4.png',
            price: 2200000,
            brand: 'AMD',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular pc',
            cpu: 'AMD Ryzen 5800X Procesador',
            motherboard: 'AMD X570 ATX Motherboard',
            ram: '32GB 3600Mhz DDR4 Dual Channel RAM',
            ssd: '2TB Nvme SSD',
            hdd: '3TB Seagate HDD',
            gpu: 'Nvidia RTX 3080TI GPU'    
        },
        {
            id: 18,
            name: 'NOTEBOOK DEAPTREAD',
            category: 'AMD',
            image: './images/pc1.png',
            price: 2200000,
            brand: 'AMD',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular pc',
            cpu: 'AMD Ryzen 5800X Procesador',
            motherboard: 'AMD X570 ATX Motherboard',
            ram: '32GB 3600Mhz DDR4 Dual Channel RAM',
            ssd: '2TB Nvme SSD',
            hdd: '3TB Seagate HDD',
            gpu: 'Nvidia RTX 3080TI GPU'    
        },
    ]
}

export default data;